name: Prevent Merging to Testing Branch

on:
  push:
    branches:
      - '*'

jobs:
  prevent_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          if [[ "${{ github.ref }}" != 'refs/heads/develop' && "${{ github.ref }}" == 'refs/heads/testing' ]]; then
            echo "Merging into testing branch is not allowed. Only merges from 'develop' branch are allowed."
            exit 1
          fi
